name: shell commands

on:
  - push 
 #env:
  #AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  #AWS_SECRET_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY }} */


jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo string
        run: echo "Pay now"
  terraform-workflows:
    runs-on: ubuntu-22.04 
    needs: ["run-shell-commands"]
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Configure AWS credentials 
        uses: aws-actions/configure-aws-credentials@v1 
        with: 
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY }} 
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY }} 
          aws-region: us-west-2
      - name: Set Terraform 
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.9
      - name: Terraform init
        run: terraform init
      - name: Terraform validate
        run: terraform validate
      - name: Terraform plan
        run: terraform plan